=== DanMasterson1/stencil/Generation/Tools/Stencil.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="items">
		<xs:complexType>
			<xs:sequence>
				<xs:choice maxOccurs="unbounded" minOccurs="1">
					<xs:element maxOccurs="unbounded" minOccurs="1" name="item">
						<xs:complexType>
							<xs:choice maxOccurs="unbounded">
								<xs:element minOccurs="1" maxOccurs="unbounded" name="field">
									<xs:complexType mixed="true">
                    
										<xs:attribute name="type" type="xs:string" use="required" />
										<xs:attribute name="dbType" type="xs:string" use="required" />
                    <xs:attribute name="foreignKey" type="xs:string" use="optional" />
                    <xs:attribute name="foreignKeyField" type="xs:string" use="optional"/>
										<xs:attribute name="isNullable" type="xs:boolean" use="required" />
										<xs:attribute name="friendlyName" type="xs:string" use="required" />
										<xs:attribute name="uiHideInList" type="xs:boolean" use="optional" />
                    <xs:attribute name="searchable" type="xs:boolean" use="optional" />
                    <xs:attribute name="sortable" type="xs:string" use="optional" />
                    <xs:attribute name="generateTokenIfEmpty" type="xs:boolean" use="optional" />
                    <xs:attribute name="sdkHidden" type="xs:boolean" use="optional" />
                    <xs:attribute name="derivedProperty" type="xs:boolean" use="optional" />
                  </xs:complexType>
								</xs:element>
                
							</xs:choice>
              
			        <xs:attribute name="name" type="xs:string" use="required" />
              <xs:attribute name="friendlyName" type="xs:string" use="required" />
              <xs:attribute name="uiDisplayField" type="xs:string" use="required" />
              <xs:attribute name="uiDefaultSort" type="xs:string" use="optional" />
              
            </xs:complexType>
					</xs:element>
          <xs:element maxOccurs="unbounded" minOccurs="1" name="enum">
          </xs:element>
				</xs:choice>
			</xs:sequence>
      
      <xs:attribute name="projectName" type="xs:string" use="required" />
      <xs:attribute name="schema" type="xs:string" use="required" />
      
		</xs:complexType>
	</xs:element>
</xs:schema>

=== DanMasterson1/stencil/Generation/XML/Entities.xml
<?xml version="1.0" encoding="utf-8"?>
<items schema="dbo" projectName="Stencil" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\Tools\Stencil.xsd">
  <item name="GlobalSetting" friendlyName="Global Setting" uiDisplayField="name">
    <field type="Guid" dbType="uniqueidentifier" isNullable="false" friendlyName="GlobalSetting ID">global_setting_id</field>
    <field type="string" dbType="nvarchar(100)" isNullable="false" searchable="true" friendlyName="Name">name</field>
    <field type="string" dbType="nvarchar(max)" isNullable="true" friendlyName="Value">value</field>
  </item>

  <item name="Brand" friendlyName="Brand" useIndex="true" indexPriority="15" indexForSearchable="true">
		<field type="Guid" dbType="uniqueidentifier" isNullable="false" friendlyName="BrandId">brand_id</field>
		<field type="string" dbType="nvarchar(100)" isNullable="false" friendlyName="BrandName" searchable="true" sortable="true">brand_name</field>
    <indexfield type="int" isNullable="false" sortable="true" friendlyName="ProductCount">product_count</indexfield>
    <indexfield type="int" isNullable="false" sortable="true" friendlyName="ListingCount">listing_count</indexfield>
	</item>

	<item name="Product" friendlyName="Product" useIndex="true" indexPriority="20" indexForSearchable="true">
		<field type="Guid" dbType="uniqueidentifier" isNullable="false" friendlyName="ProductId">product_id</field>
    <field type="Guid" dbType="uniqueidentifier" foreignKey="Brand" foreignKeyField="brand_id" isNullable="false" friendlyName="BrandId" iInvalidateforeignKey="false" foreignKeyInvalidatesMe="true" >brand_id</field>
		<field type="string" dbType="nvarchar(100)" isNullable="false" friendlyName="ProductName" searchable="true" sortable="true">product_name</field>
    <field type="string" dbType="nvarchar(4000)" isNullable="false" friendlyName="ProductDescription" searchable="true">product_description</field>
    <field type="decimal" dbType="decimal(5,2)" isNullable="false" friendlyName="BasePrice" sortable="true">baseprice</field>
    <indexfield type="string" isNullable="false" sortable="true" computedFrom="Brand" computedReferenceField="brand_id" computedBy="Extra" friendlyName="BrandName">brand_name</indexfield>
	</item>

  <item name="Promotion" friendlyName="Promotion" useIndex="true" indexPriority="25" indexForSearchable="true">
    <field type="Guid" dbType="uniqueidentifier" isNullable="false" friendlyName="PromotionId">promotion_id</field>
    <field type="string" dbType="nvarchar(500)" isNullable="false" friendlyName="PromotionDescription">promotion_description</field>
    <field type="decimal" dbType="decimal(5,2)" isNullable="false" friendlyName="PromotionPercent">percent</field> 
  </item>

  <item name="Listing" friendlyName="Listing" useIndex="true" indexPriority="30" indexForSearchable="true">
    <field type="Guid" dbType="uniqueidentifier" isNullable="false" friendlyName="ListingId">listing_id</field>
    <field type="Guid" dbType="uniqueidentifier" isNullable="false" foreignKey="Brand" foreignKeyField="brand_id" friendlyName="BrandId" iInvalidateforeignKey="false" foreignKeyInvalidatesMe="true">brand_id</field>
    <field type="Guid" dbType="uniqueidentifier" isNullable="false" foreignKey="Product" foreignKeyField="product_id" friendlyName="ProductId" iInvalidateforeignKey="false" foreignKeyInvalidatesMe="true">product_id</field>
    <field type="Guid" dbType="uniqueidentifier" isNullable="true" foreignKey="Promotion" foreignKeyField="promotion_id" friendlyName="PromotionId" iInvalidateforeignKey="false" foreignKeyInvalidatesMe="true">promotion_id</field>
    <field type="string" dbType="nvarchar(500)" isNullable="true" friendlyName="ListingDescription" searchable="true">listing_description</field>
    <field type="bool" dbType="bit" isNullable="false" friendlyName="Active">active</field> 
    <field type="DateTime" dbType="datetimeoffset(0)" isNullable="false" friendlyName="ExpireDate">expire_utc</field>
    <indexfield type="decimal" isNullable="false" sortable="true" friendlyName="ListingPrice">listing_price</indexfield> 
    <indexfield type="decimal" isNullable="false" sortable="true" friendlyName="ProductBasePrice">product_baseprice</indexfield>
    <indexfield type="decimal" isNullable="true" friendlyName="PromotionPercent">promotion_percent</indexfield>
    <indexfield type="string" isNullable="false" sortable="true" computedFrom="Brand" computedReferenceField="brand_id" computedBy="Extra" friendlyName="BrandName">brand_name</indexfield> 
    <indexfield type="string" isNullable="false" sortable="true" computedFrom="Product" computedReferenceField="product_id" computedBy="Extra" friendlyName="ProductName">product_name</indexfield>
    <indexfield type="string" isNullable="true" sortable="true"  friendlyName="PromotionDescription">promotion_description</indexfield>
  </item>

  <item name="Order" friendlyName="Order" useIndex="true" indexPriority="35" indexForSearchable="true">
    <field type="Guid" dbType="uniqueidentifier" isNullable="false" friendlyName="ListingId">order_id</field>
    <field type="Guid" dbType="uniqueidentifier" isNullable="false" foreignKey="Account" foreignKeyField="account_id" friendlyName="AccountId" iInvalidateforeignKey="false" foreignKeyInvalidatesMe="true">account_id</field>
    <field type="Guid" dbType="uniqueidentifier" isNullable="true" foreignKey="Invoice" foreignKeyField="invoice_id" friendlyName="InvoiceId" iInvalidateforeignKey="true" foreignKeyInvalidatesMe="false">invoice_id</field>
    <field type="Guid" dbType="uniqueidentifier" isNullable="true" foreignKey="Payment" foreignKeyField="payment_id" friendlyName="PaymentId" iInvalidateforeignKey="true" foreignKeyInvalidatesMe="true">payment_id</field>
    <field type="Guid" dbType="uniqueidentifier" isNullable="true" foreignKey="Shipment" foreignKeyField="shipment_id" friendlyName="ShipmentId" iInvalidateforeignKey="true" foreignKeyInvalidatesMe="true">shipment_id</field>
    <field type="bool" dbType="bit" isNullable="false" friendlyName="OrderPaid">order_paid</field> 
    <field type="bool" dbType="bit" isNullable="false" friendlyName="OrderShipped">order_shipped</field> 
    <field type="OrderStatus" dbType="int" isNullable="false" friendlyName="OrderStatus">order_status</field>
    <indexfield type="decimal" isNullable="false" sortable="true"  friendlyName="OrderTotal">order_total</indexfield>
    <indexfield type="DateTime" isNullable="false" sortable="true"  friendlyName="CreatedUtc">created_utc</indexfield>
    <indexfield type="string" isNullable="false" sortable="true" friendlyName="AccountName">account_name</indexfield>
    <indexfield type="string" isNullable="false" sortable="true" friendlyName="AccountEmail">account_email</indexfield>
    <indexfield type="string" isNullable="false" sortable="true" friendlyName="ShipmentAddress">shipment_address</indexfield>
    <indexfield type="string" isNullable="false" sortable="true" friendlyName="PaymentCardType">payment_cardtype</indexfield>
    <indexfield type="string" isNullable="false" sortable="true" friendlyName="Status">status</indexfield>
    <indexfield type="int" isNullable="false" sortable="true" friendlyName="LineItemCount">lineitem_count</indexfield>
    <indexfield type="Product[]" isNullable="false" sortable="true" friendlyName="Products">products</indexfield>
  </item>

  <item name="LineItem" friendlyName="LineItem" useIndex="true" indexPriority="40" indexForSearchable="true">
     <field type="Guid" dbType="uniqueidentifier" isNullable="false" friendlyName="LineItemId">lineitem_id</field>
     <field type="Guid" dbType="uniqueidentifier" isNullable="false" foreignKey="Order" foreignKeyField="order_id" friendlyName="OrderId" iInvalidateforeignKey="true" foreignKeyInvalidatesMe="true">order_id</field>
     <field type="Guid" dbType="uniqueidentifier" isNullable="false" foreignKey="Listing" foreignKeyField="listing_id" friendlyName="ListingId" iInvalidateforeignKey="false" foreignKeyInvalidatesMe="true">listing_id</field>
     <field type="int" dbType="int" isNullable="false" friendlyName="LineItemQuantity">lineitem_quantity</field>
     <indexfield type="decimal" isNullable="false" friendlyName="ListingPrice">listing_price</indexfield>
     <indexfield type="decimal" isNullable="false" friendlyName="LineItemTotal">lineitem_total</indexfield>
  </item>

  <item name="Invoice" friendlyName="Invoice" useIndex="true" indexPriority="45" indexForSearchable="true">
    <field type="Guid" dbType="uniqueidentifier" isNullable="false" friendlyName="InvoiceId">invoice_id</field>
    <field type="Guid" dbType="uniqueidentifier" isNullable="false" foreignKey="Order" foreignKeyField="order_id" friendlyName="OrderId" iInvalidateforeignKey="true" foreignKeyInvalidatesMe="true">order_id</field>
    <field type="Guid" dbType="uniqueidentifier" isNullable="false" foreignKey="Asset" foreignKeyField="asset_id" friendlyName="AssetId" iInvalidateforeignKey="false" foreignKeyInvalidatesMe="true">asset_id</field>
    
  </item>

  <item name="Payment" friendlyName="Payment" useIndex="true" indexPriority="50" indexForSearchable="true">
    <field type="Guid" dbType="uniqueidentifier" isNullable="false" friendlyName="PaymentId">payment_id</field>
    <field type="Guid" dbType="uniqueidentifier" isNullable="false" foreignKey="Order" foreignKeyField="order_id" friendlyName="OrderId" iInvalidateforeignKey="true" foreignKeyInvalidatesMe="true">order_id</field>
    <field type="bool" dbType="bit" isNullable="false">payment_processed_successful</field>
    <field type="CardType" dbType="int" isNullable="false">card_type</field>
    <field type="string" dbType="nvarchar(50)" isNullable="false">card_number</field>
    <field type="DateTime" dbType="DateTime" isNullable="false">expire_date</field>
    <field type="int" dbType="int">cvv</field>
    <field type="bool" dbType="bit">save_paymentdetails</field>
  </item>
